parameters:
#    nireak_blog.example.class: Nireak\Bundle\BlogBundle\Example

services:
#    nireak_blog.example:
#        class: %nireak_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
